export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const SHOP_ROUTE = '/'
export const THING_ROUTE = '/thing'
export const BASKET_ROUTE = '/basket'